# Generated by Django 5.0.3 on 2024-04-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
